apiVersion: v1
kind: Service
metadata:
  name: yarn-re-mn
  labels:
    statefulset.kubernetes.io/pod-name: yarn-rm-0
  namespace: yarn-cluster
spec:
  type: NodePort
  ports:
  - port: 8088
    nodePort: 8088
    targetPort: 8088
    name: yarn-web
#  - port: 9000
#    nodePort: 19000
#    targetPort: 9000
#    name: hdfs-9000
#  - port: 8088
#    nodePort: 18088
#    targetPort: 8088
#    name: yarn-web
#  - port: 8188
#    nodePort: 18118
#    targetPort: 8188
#    name: history-web
#  - port: 8082
#    nodePort: 18082
#    targetPort: 18082
#    name: yarn-8082
  selector:
    component: yarn-rm
    statefulset.kubernetes.io/pod-name: yarn-rm-0
